### PR TITLE
Update bgc_trip.dataresource.yaml

### PR DESCRIPTION
**Pull request by sedgar**

### CODE REVIEW

**Comment by mhidas** [comment]
@sedgar Please let me know when this pull request is ready to review.

Note that while you're still working on a PR and intending to add more commits, you can mark it as a draft. This can be done at the time you first create the PR, or can be changed later. See the top right of this window, where it says "Still in progress? Convert to draft"

image

When you have added all the changes you want to include, you can mark it as "ready for review", and optionally request a review from specific people (though in general I'll look at any PR that is put up here).

**Comment by sedgar** [comment]
Thanks Marty. I think it's actually ready, but I'll be looking at starting a new pull request for the next block of work very soon, so that will be a good time to review this and mark it as ready for review.

**Review by mhidas — APPROVED** [review]
These changes seem fine to me.

**Comment by mhidas** [comment]
@sedgar Something I just noticed - the deprecated file `bgc_phyto_countraw.dataresource.yaml` is still on your [bgc](https://github.com/aodn/public-schema/tree/bgc/bgc_data) branch, whereas it has already been removed in the [master](https://github.com/aodn/public-schema/tree/master/bgc_data) branch. This because you just added the new changes to your existing local branch (from PR #2), pushed them up and created the PR from that.

No big deal, the problem will go away when I merge this PR (i.e. it won't re-add the unwanted file on the master branch). I just wanted to mention it because ideally when you start creating a new set of changes, the workflow should be:
* check out the master branch and pull down the latest changes;
* create a _new_ branch (they don't cost anything, so no need to recycle);
* commit your changes;
* push your new branch up to GitHub and create a new pull request.

Let me know if I can help with any of these steps...

**Pull request merged**
